import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {createApp} from '../apps/web/server.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));const output=root+'docs/evidence';await mkdir(output,{recursive:true});
let server;const base=process.env.TEST_BASE_URL||await new Promise(resolve=>{server=createApp({env:{}});server.listen(0,'127.0.0.1',()=>resolve('http://'+'127.0.0.1:'+server.address().port));});
// Use the existing sandbox browser; CI/local users without it launch an isolated headless browser.
const shared=Boolean(process.env.AGENT_BROWSER_CDP);
const browser=shared?await chromium.connectOverCDP(process.env.AGENT_BROWSER_CDP):await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||(existsSync('/usr/local/bin/chromium')?'/usr/local/bin/chromium':undefined),args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
await context.addInitScript(()=>{Object.defineProperty(window,'ethereum',{value:undefined,writable:true,configurable:true});});
const page=await context.newPage();page.setDefaultTimeout(12000);
const exceptions=[],results=[];page.on('pageerror',e=>exceptions.push(e.message));
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS',name);}catch(e){results.push({name,status:'FAIL',error:e.message});console.error('FAIL',name,e);throw e;}}
async function text(selector,value){await page.waitForFunction(({selector,value})=>document.querySelector(selector)?.textContent?.includes(value),{selector,value});}
async function capture(file,fullPage=true){if(fullPage){const dismiss=page.getByRole('button',{name:'Dismiss notification',exact:true});if(await dismiss.isVisible())await dismiss.click();await page.evaluate(()=>{document.activeElement?.blur?.();scrollTo(0,0);});}await page.screenshot({path:output+'/'+file,fullPage});}
async function noOverflow(){const widths=await page.evaluate(()=>({body:document.body.scrollWidth,doc:document.documentElement.scrollWidth,view:innerWidth}));assert.ok(widths.doc<=widths.view+1&&widths.body<=widths.view+1,JSON.stringify(widths));}
let failed=false;
try{
 await check('Server market initializes session and four reserve-derived numbers',async()=>{await page.goto(base+'/market');await text('[data-testid="stat-0"]','63.0%');await text('[data-testid="stat-1"]','$185.00');await text('[data-testid="stat-2"]','$118.00');await text('[data-testid="stat-3"]','+$67.00');await noOverflow();await capture('market-desktop.png',true);});
 await check('Invalid input returns a visible error without a trade',async()=>{await page.getByLabel('Amount to spend').fill('0');await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/positive/);await text('.balance-box strong','$5,000.00');});
 await check('Asset buy reviews and confirms an actual sandbox fill',async()=>{await page.getByLabel('Amount to spend').fill('25');await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();await page.getByRole('dialog',{name:'Review your trade'}).waitFor();await page.getByRole('button',{name:'Confirm sandbox trade',exact:true}).click();await text('.balance-box strong','$4,975.00');assert.notEqual(await page.locator('[data-testid="stat-1"]').innerText(),'$185.00');});
 await check('Local clipping visibly changes a requested 1000 into a 50 fill',async()=>{await page.getByLabel('Amount to spend').fill('1000');await page.getByLabel('Try the local size clip').check();await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();const d=page.getByRole('dialog');await d.waitFor();assert.match(await d.innerText(),/Requested \$1,000.00 → public fill \$50.00/);await capture('trade-review-desktop.png',false);await d.getByRole('button',{name:'Confirm sandbox trade',exact:true}).click();await text('.balance-box strong','$4,925.00');await page.getByLabel('Try the local size clip').uncheck();});
 await check('Binary NO fill changes the event probability',async()=>{await page.getByRole('button',{name:'The event',exact:true}).click();await page.getByRole('button',{name:/Buy NO/}).click();await page.getByLabel('Amount to spend').fill('100');const before=await page.locator('[data-testid="stat-0"]').innerText();await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();await page.getByRole('button',{name:'Confirm sandbox trade',exact:true}).click();await text('.balance-box strong','$4,825.00');assert.notEqual(await page.locator('[data-testid="stat-0"]').innerText(),before);});
 await check('Stale quote fails without silently refilling',async()=>{await page.getByLabel('Amount to spend').fill('25');await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();await page.getByRole('dialog').waitFor();await page.evaluate(async()=>{const c=await (await fetch('/api/config')).json();await fetch('/api/sandbox/pairs',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':c.csrf},body:JSON.stringify({book:'binary',action:'split',quantity:'1'})});});await page.getByRole('button',{name:'Confirm sandbox trade',exact:true}).click();await page.getByRole('dialog').getByRole('alert').waitFor();assert.match(await page.getByRole('dialog').innerText(),/Prices changed/);await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'detached'});});
 await check('Split pairs create binary and asset complete sets',async()=>{await page.locator('.desktop-nav').getByRole('link',{name:'Positions',exact:true}).click();await page.getByLabel('Book',{exact:true}).selectOption('asset');await page.getByRole('button',{name:'Split pair',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent?.includes('Split 1'));await page.getByLabel('Book',{exact:true}).selectOption('binary');await page.getByLabel('Number of pairs').fill('10');await page.getByRole('button',{name:'Split pair',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent?.includes('Split 10'));await capture('positions-desktop.png',true);});
 await check('Two-stage flow: resolve event freezes binary and losing leg while allowing surviving leg trade',async()=>{await page.locator('.desktop-nav').getByRole('link',{name:'How it works',exact:true}).click();await page.getByRole('button',{name:'1. Resolve event',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent?.includes('Sandbox event resolved as YES'));await page.locator('.desktop-nav').getByRole('link',{name:'Market',exact:true}).click();await page.getByRole('button',{name:'The event',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Binary book closed',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'The asset',exact:true}).click();await page.getByRole('button',{name:/Buy NO/}).click();assert.equal(await page.getByRole('button',{name:'Losing leg frozen',exact:true}).isDisabled(),true);await page.getByRole('button',{name:/Buy YES/}).click();await page.getByLabel('Amount to spend').fill('25');await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();await page.getByRole('dialog',{name:'Review your trade'}).waitFor();await page.getByRole('button',{name:'Confirm sandbox trade',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent?.includes('Sandbox trade filled'));});
 await check('Binary-first claims succeed while preserving asset and residual positions',async()=>{await page.locator('.desktop-nav').getByRole('link',{name:'Positions',exact:true}).click();await page.getByRole('button',{name:'Claim sandbox payout',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent?.includes('Claimed $11.00'));const tableText=await page.locator('.portfolio-layout table').innerText();assert.match(tableText,/Residual claim \(R\)/);assert.match(tableText,/sNVDA share/);await page.getByRole('button',{name:'Claim sandbox payout',exact:true}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').innerText(),/asset claims unlock after price fixing/);});
 await check('Fix price settles market, stops trading, and unlocks final asset and residual payouts',async()=>{await page.locator('.desktop-nav').getByRole('link',{name:'How it works',exact:true}).click();await page.getByLabel('Reported synthetic index').fill('200');await page.getByRole('button',{name:'2. Fix price & settle',exact:true}).click();await page.locator('.settled-summary').waitFor();assert.match(await page.locator('.settled-summary').innerText(),/\$200.00/);assert.match(await page.locator('.settled-summary').innerText(),/\$300.00/);await capture('settlement-desktop.png',true);await page.locator('.desktop-nav').getByRole('link',{name:'Market',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Market settled',exact:true}).isDisabled(),true);await page.locator('.desktop-nav').getByRole('link',{name:'Positions',exact:true}).click();await page.getByRole('button',{name:'Claim sandbox payout',exact:true}).click();await page.getByRole('heading',{name:'No positions yet.',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent?.includes('Claimed'));});
 await check('Reset is explicit and restores the original market',async()=>{await page.locator('.desktop-nav').getByRole('link',{name:'Market',exact:true}).click();await page.locator('.balance-box').getByRole('button',{name:'Reset sandbox',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Reset sandbox',exact:true}).click();await text('[data-testid="stat-0"]','63.0%');await text('.balance-box strong','$5,000.00');});
 await check('Unconfigured Arc mode clears all sandbox prices',async()=>{await page.getByRole('button',{name:'Arc Testnet',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-testid="stat-0"]')?.textContent==='—');assert.match(await page.getByRole('alert').innerText(),/not configured/);assert.equal(await page.getByRole('button',{name:'Deployment not configured',exact:true}).isDisabled(),true);});
 await check('Missing wallet has an actionable error, no fabricated connection',async()=>{await page.locator('.site-header').getByRole('button',{name:'Connect wallet',exact:true}).click();await page.waitForFunction(()=>document.body.textContent.includes('No injected wallet found'));});
 await check('Landing CTA, product preview, FAQ and reduced-motion behavior',async()=>{await page.getByRole('button',{name:'Sandbox',exact:true}).click();await page.locator('.site-header').getByRole('link',{name:'THELEMA',exact:true}).click();await page.getByRole('heading',{level:1}).waitFor();await noOverflow();await page.locator('.tagline-section').scrollIntoViewIfNeeded();assert.equal(await page.locator('.reveal-word').first().evaluate(e=>getComputedStyle(e).opacity),'1');await page.locator('.faq-list summary').first().click();assert.equal(await page.locator('.faq-list details').first().getAttribute('open'),'');await page.evaluate(()=>scrollTo(0,0));await capture('landing-desktop.png',true);});
 await check('390px mobile menu, market, quote and no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});await page.goto(base+'/market');await text('[data-testid="stat-0"]','63.0%');await noOverflow();await capture('market-mobile.png',true);await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('dialog',{name:'Explore THELEMA'}).waitFor();await page.getByRole('dialog').getByRole('link',{name:/How it works/}).click();await page.getByRole('heading',{name:'Know what’s running.',exact:true}).waitFor();await noOverflow();await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'detached'});});
 await check('320px layout and custom 404 remain usable',async()=>{await page.setViewportSize({width:320,height:740});await page.goto(base+'/market');await text('[data-testid="stat-0"]','63.0%');await noOverflow();await page.goto(base+'/does-not-exist');await page.getByRole('heading',{name:'This page hasn’t happened.',exact:true}).waitFor();await noOverflow();});
 await check('Standalone file works without server calls and completes a trade',async()=>{await page.setViewportSize({width:1440,height:900});const network=[];page.on('request',r=>{if(r.url().startsWith('http'))network.push(r.url());});await page.goto(new URL('file://'+root+'THELEMA-preview.html').href);await text('[data-testid="stat-0"]','63.0%');await page.getByRole('button',{name:'Review sandbox trade',exact:true}).click();await page.getByRole('button',{name:'Confirm sandbox trade',exact:true}).click();await text('.balance-box strong','$4,975.00');assert.deepEqual(network,[]);await page.locator('.site-header').getByRole('link',{name:'THELEMA',exact:true}).click();await page.setViewportSize({width:390,height:844});await noOverflow();await capture('landing-mobile.png',true);});
 await check('No uncaught JavaScript errors occurred',async()=>assert.deepEqual(exceptions,[]));
}catch(e){failed=true;await capture('browser-failure.png',true).catch(()=>{});}
finally{
 await writeFile(output+'/browser-results.json',JSON.stringify({scope:'Local UI and standalone preview only; wallet absence is simulated; no live integrations executed',passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results,exceptions},null,2));
 for(const p of context.pages())await p.close();await context.close();
 if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}
 console.log(JSON.stringify({passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length}));
 // Exit disconnects the CDP client without destroying the shared user-visible browser.
 process.exit(failed?1:0);
}
