import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdir} from 'node:fs/promises';import {fileURLToPath} from 'node:url';
import {encode,selector} from '../packages/arc/abi.mjs';
const a=i=>'0x'+i.toString(16).padStart(40,'0'),word=n=>'0x'+BigInt(n).toString(16).padStart(64,'0');
const config={arcReady:true,collateral:'0x3600000000000000000000000000000000000000',contracts:{binaryAMM:a(1),yesShareAMM:a(2),noShareAMM:a(3),binarySplit:a(4),shareSplit:a(5),oracle:a(6)}};
await mkdir(new URL('./.generated/',import.meta.url),{recursive:true});
await build({entryPoints:[fileURLToPath(new URL('../apps/web/src/wallet.ts',import.meta.url))],outfile:fileURLToPath(new URL('./.generated/wallet.mjs',import.meta.url)),bundle:true,platform:'node',format:'esm',target:'es2022',logLevel:'silent'});
const {connectWallet,sendArcTrade}=await import('./.generated/wallet.mjs');
const quote=()=>({book:'asset',side:'yes',amount:'25',outUnits:'200000000000000000',quantity:'0.2',minOutUnits:'199000000000000000',fee:'0.075',averagePrice:125,priceImpactPct:1,slippageBps:50,revision:1,expiresAt:Date.now()+120000,mode:'arc'});
function mock({allowance=0n,chain=5042002,decimals=6,onSend,revert=false}={}){const sent=[],calls=[],state={account:a(9),chain};globalThis.window={ethereum:{request:async({method,params=[]})=>{calls.push(method);if(method==='eth_chainId')return '0x'+state.chain.toString(16);if(method==='eth_requestAccounts'||method==='eth_accounts')return [state.account];if(method==='wallet_switchEthereumChain'){state.chain=5042002;return null;}if(method==='eth_call'){const d=params[0].data.slice(0,10);if(d===selector('decimals()'))return word(decimals);if(d===selector('allowance(address,address)'))return word(allowance);if(d===selector('balanceOf(address)'))return word(5000000000n);return word(1);}if(method==='eth_estimateGas')return '0x186a0';if(method==='eth_sendTransaction'){sent.push(params[0]);onSend?.(params[0],state);return '0x'+String(sent.length).padStart(64,'0');}if(method==='eth_getTransactionReceipt')return {status:revert?'0x0':'0x1'};throw Error('Unexpected mocked method '+method);}}};return {sent,calls,state};}
test('MOCK wallet connection checks Arc and six-decimal balance',async()=>{const m=mock();const w=await connectWallet(config);assert.equal(w.account,a(9));assert.equal(w.balance,'5000');assert.ok(m.calls.includes('wallet_switchEthereumChain'));assert.equal(m.sent.length,0);});
test('MOCK wallet rejects wrong network before any transaction',async()=>{const m=mock({chain:1});await assert.rejects(sendArcTrade(quote(),config,a(9)),/Switch/);assert.equal(m.sent.length,0);});
test('MOCK wallet rejects wrong decimals before approval',async()=>{const m=mock({decimals:18});await assert.rejects(sendArcTrade(quote(),config,a(9)),/decimals/);assert.equal(m.sent.length,0);});
test('MOCK wallet creates only exact allowance and simulates each transaction',async()=>{const m=mock();const q=quote();await sendArcTrade(q,config,a(9));assert.equal(m.sent.length,2);assert.equal(m.sent[0].to,config.collateral);assert.equal(m.sent[0].data,encode('approve(address,uint256)',[config.contracts.yesShareAMM,25000000n]));assert.equal(m.sent[1].to,config.contracts.yesShareAMM);assert.equal(m.sent[1].chainId,'0x'+(5042002).toString(16));assert.equal(m.sent[1].data,encode('buyShares(uint256,uint256,uint256)',[25000000n,BigInt(q.minOutUnits),BigInt(Math.floor(q.expiresAt/1000))]));assert.equal(m.calls.filter(x=>x==='eth_estimateGas').length,2);});
test('MOCK wallet resets a smaller existing allowance before exact approval',async()=>{const m=mock({allowance:1n});await sendArcTrade(quote(),config,a(9));assert.equal(m.sent.length,3);assert.equal(m.sent[0].data,encode('approve(address,uint256)',[config.contracts.yesShareAMM,0n]));});
test('MOCK wallet does not request unnecessary new approval',async()=>{const m=mock({allowance:25000000n});await sendArcTrade(quote(),config,a(9));assert.equal(m.sent.length,1);assert.equal(m.sent[0].to,config.contracts.yesShareAMM);});
test('MOCK wallet rejects stale or zero-minimum quotes before signing',async()=>{const m=mock();await assert.rejects(sendArcTrade({...quote(),expiresAt:Date.now()-1},config,a(9)),/expired/);await assert.rejects(sendArcTrade({...quote(),minOutUnits:'0'},config,a(9)),/positive/);assert.equal(m.sent.length,0);});
test('MOCK wallet acknowledges an approval can remain after quote expiry',async()=>{const q=quote(),m=mock({onSend:()=>{q.expiresAt=Date.now()-1;}});await assert.rejects(sendArcTrade(q,config,a(9)),/Approval remains/);assert.equal(m.sent.length,1);});
test('MOCK wallet guards account changes between approval and fill',async()=>{const m=mock({onSend:(_,state)=>{state.account=a(10);}});await assert.rejects(sendArcTrade(quote(),config,a(9)),/account changed/);assert.equal(m.sent.length,1);});
test('MOCK wallet does not report a reverted receipt as success',async()=>{const m=mock({allowance:25000000n,revert:true});await assert.rejects(sendArcTrade(quote(),config,a(9)),/reverted/);assert.equal(m.sent.length,1);});
